name: running test

permissions:
  contents: write     
  actions: write
  checks: write

on:
  push:
    branches:
      - feature/test/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setting up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: running tests
        run: npx cypress run --env filename=$(ls -t uploads/cypress.env.json-* | head -n1 | xargs basename)

      - name: upload the results
        uses: actions/upload-artifact@v4
        with:
          name: test-repporting
          path: cypress/reports/mochawesome_001.html

      - name : delete the branch
        env :
          GITHUB_TOKEN: ${{secrets.TOKEN_PIPELINE}}
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          git fetch origin main
          git checkout origin/main
          git branch -D $CURRENT_BRANCH 
          git push origin -d $CURRENT_BRANCH

      # - name : download the results file
      #   uses: actions/download-artifact@v4

      - name: upload file to report test api
        run: |
          curl -X POST https://7a99-41-140-20-55.ngrok-free.app/reportingtest/upload \
            -H "Content-Type: multipart/form-data" \
            -F "file=@src/report.html" \
