name: running test

on:
  push:
    branches:
      - feature/test/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setting up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: running tests
        run: npx cypress run

      - name: upload the results
        uses: actions/upload-artifact@v4
        with:
          name: test-repporting
          path: cypress/reports/mochawesome_001.html

      # - name : download the results file
      #   uses: actions/download-artifact@v4

      # - name: upload file to report test api
      #   run: |
      #     curl -X POST http://localhost:3000/reportingtest/upload \
      #       -H "Content-Type: multipart/form-data" \
      #       -F "file=@src/report.html" \
